### ISSUE TITLE
Automate vim plugin installation

### ISSUE THREAD

**Issue by davidpolverari** [diegorubin/environment#1]
I know that's none of my business, but as I made Ansible roles to automate my Debian laptop config too, here is a suggestion you could use to avoid having to install neovim plugins by hand after running your playbooks:
```
- name: Install Vundle plugins declared in .vimrc
  become: no
  shell: >
    vim
    +PluginInstall
    +qall!
```
With a task like this I automated my Vundle plugin installation inside my vim role. I hope it helps.

**Comment by diegorubin** [comment]
@davidpolverari, I implemented your suggestion.
Thank you.

**Comment by davidpolverari** [comment]
I'm glad it was useful to you! You're welcome!
